---
title: "analyse_clusters"
author: "Gitte Aasbjerg"
date: "23/11/2020"
output: html_document
---

### Exrtact gene names and ES values from CELLEX output
```{r}
library(dplyr)
library(Seurat)

# Load data
esmu.zhong <- read.csv(file = '../data/Zhong2_cellex_human/Zhong2_hippocampus_mouse_cells.esmu.csv.gz')
esmu.saunders <- read.csv(file = '/home/cbmr/qwn903/my_tools/output/saunders_mousebrain_Hippocampus_ens.esmu.csv.gz')

```

```{r}

# Extract only non-zero ES values and sort genes based on ES
saunders.non_zero <- esmu.saunders %>%
  select(gene, Neuron.Slc17a7.Calb2_Vgll3) %>%
  arrange(desc(Neuron.Slc17a7.Calb2_Vgll3)) %>%
  filter(Neuron.Slc17a7.Calb2_Vgll3 > 0)

zhong.non_zero <- esmu.zhong %>%
  select(gene, X8) %>%
  arrange(desc(X8)) %>%
  filter(X8 > 0)

# Save dataframe of genes and ES values 
write.csv(zhong.non_zero, file = "../data/zhong_cellex_X8_cellex_genes.csv")
write.csv(saunders.non_zero, file = "../data/saunders_cellex_Neuron.Slc17a7.Calb2_Vgll3_cellex_genes.csv")
```



### Find genes that overlap between cluster from Zhong and Saunders
```{r}
# Load list of genes expressed in relevant cluster(s) 
gene.saunders <- read.csv(file = '../data/genelist/saunders_cellex_Neuron.Slc17a7.Calb2_Vgll3_cellex_genes.csv',sep = ";")
gene.zhong <- read.csv(file = '../data/genelist/zhong_cellex_X8_cellex_genes.csv', sep = ";")

# Filter data on ES threshold
ES_threshold <- 0.2

gene.zhong <- gene.zhong[gene.zhong$ES>ES_threshold,]
gene.saunders <- gene.saunders[gene.saunders$ES>ES_threshold,]

```


```{r}
library('GeneOverlap')

# Perform hypergeometric test on genes from the two clusters 
go <- newGeneOverlap(gene.saunders$Gene, gene.zhong$Gene)
go.obj <- testGeneOverlap(go)
go.obj
```


```{r}

# Detect genes present in both clusters
gene.overlap <- intersect(gene.saunders$Gene, gene.zhong$Gene)

# Extract overlapping genes and coresponding ES values 
s <- gene.saunders[gene.saunders$Gene %in% gene.overlap,] %>%
  arrange(desc(Gene)) %>%
  rename(gene = 1, saunders = 2)   %>%
  mutate(saunders = as.numeric(saunders))

z <- gene.zhong[gene.zhong$Gene %in% gene.overlap,] %>%
  arrange(desc(Gene)) %>%
  rename(delete = 1, zhong = 2) %>%
  mutate(zhong = as.numeric(zhong)) 

# Merge gene-names with corresponding ES values for saunders and zhong
sz <- cbind(z,s) %>% 
  select(-1) %>%
  mutate(product = zhong * saunders) %>%
  column_to_rownames(var = "gene") %>%
  arrange(desc(product)) 

# Save as csv
write.csv(sz, file = "../data/overlapping_genes.csv")

```





### Transfer labels from Saunders to Zhong
```{r}
# Read and perform SCTransform on saunders data
data.zhong <- readRDS("../data/Zhong_SCTransformed.rds")
data.saunders <- readRDS("/data/pub-others/saunders-mousebrain-2018/seurat_obj/saunders_hippocampus.annotated2018.seurat_obj.RDS.gz")

# SCTransform data to enable detection of anchors
data.saunders <- SCTransform(data.saunders, verbose = FALSE, )

# find transfer anchors
hip.anchors <- FindTransferAnchors(reference = data.saunders, normalization.method = "SCT",
                                        query = data.zhong, dims = 1:30, reference.assay = "SCT",
                                        query.assay = "SCT", reduction = "cca")
```


```{r}
library('tidyverse')

# Tissue
predictions_tissue <- TransferData(anchorset = hip.anchors,
                            refdata = data.saunders@meta.data$tissue, dims = 1:30, weight.reduction = "cca")

predictions_tissue <- predictions_tissue %>% 
  select(predicted.id, prediction.score.max) %>% 
  rename(prediction.tissue = predicted.id, tissue.score =prediction.score.max) %>%
  rownames_to_column() 


# Full name
predictions_fullname <- TransferData(anchorset = hip.anchors,
                            refdata = data.saunders@meta.data$full_name, dims = 1:30, weight.reduction = "cca")

predictions_fullname <- predictions_fullname %>% 
  select(predicted.id, prediction.score.max) %>% 
  rename(prediction.full_name = predicted.id, full_name.score =prediction.score.max) %>%
  rownames_to_column() 


# Tissue Subcluster
predictions_tissue_subcluster <- TransferData(anchorset = hip.anchors,
                            refdata = data.saunders@meta.data$tissue_subcluster, dims = 1:30, weight.reduction = "cca")

predictions_tissue_subcluster <- predictions_tissue_subcluster %>% 
  select(predicted.id, prediction.score.max) %>% 
  rename(prediction.tissue_subcluster = predicted.id, tissue_subcluster.score =prediction.score.max) %>%
  rownames_to_column() 


# Common name
predictions_commonname <- TransferData(anchorset = hip.anchors,
                            refdata = data.saunders@meta.data$common_name, dims = 1:30, weight.reduction = "cca")

predictions_commonname <- predictions_commonname %>% 
  select(predicted.id, prediction.score.max) %>% 
  rename(prediction.common_name = predicted.id, common_name.score =prediction.score.max) %>%
  rownames_to_column() 


# Class
predictions_class <- TransferData(anchorset = hip.anchors,
                            refdata = data.saunders@meta.data$class, dims = 1:30, weight.reduction = "cca")

predictions_class <- predictions_class %>% 
  select(predicted.id, prediction.score.max) %>% 
  rename(prediction.class = predicted.id, class.score =prediction.score.max) %>%
  rownames_to_column() 
```


```{r}
# Joined together
meta <- left_join(predictions_tissue, predictions_fullname,) %>% 
  left_join(.,predictions_tissue_subcluster) %>%
  left_join(.,predictions_commonname) %>%
  left_join(.,predictions_class) %>%
  remove_rownames %>% 
  column_to_rownames(var="rowname")


# Merge joined meta-data with seurat object and safe as RDS
data.zhong <- AddMetaData(data.zhong, metadata = meta)
saveRDS(data.zhong, file = "../data/Zhong_w_metadata.rds")
```


```{r}
# Visual analysis
VlnPlot(data.zhong, c("CALB2", "VGLL3","VIP","CD44","PDE11A", "CCK"), group.by = "prediction.class", pt.size = 0.5)
```



### Analyse gene markers with Seurat
```{r}
# Find cluster markers of relevant clusters
Idents(object = data) <- data@meta.data$seurat_clusters
cluster9.markers <- FindMarkers(data, ident.1 = 9, min.pct = 0.25)
cluster8.markers <- FindMarkers(data, ident.1 = 8, min.pct = 0.25)
cluster4.markers <- FindMarkers(data, ident.1 = 4, min.pct = 0.25)
```

