---
title: "pvalue_adjusting"
author: "Gitte Aasbjerg"
date: "17/11/2020"
output: html_document
---

# Load file
```{r}
library(dplyr)
prioritization <- read.csv(file = '../../code/CELLECT/saunders3/CELLECT-LDSC/results/prioritization.csv')
```

# Calculate adjusted pvalues
```{r}
unique_gwas <- as.list(unique(prioritization$gwas))

new_pvalues_total <- list()

for (i in 1:length(unique_gwas)){
  
  # Extract GWAS
  gwas <- prioritization[which(prioritization$gwas==unique_gwas[[i]]),]
  
  # calculate adjusted p-values
  new_pvalue <- as.list(p.adjust(gwas$pvalue, method = p.adjust.methods, n = nrow(gwas)))
  
  # Append adjusted p-values to list of all new values
  new_pvalues_total = c(new_pvalues_total, new_pvalue)
}
```

# Add adjusted pvalues to original data frame
```{r}

# Add adjusted p value to dataframe
prioritization$pvalue_adjusted <- new_pvalues_total

# Find instances of gwas with adjusted p-value above 0.05, and filter so only the top 3 are present
significant <- prioritization[prioritization$pvalue_adjusted<0.05,] %>%
  group_by(gwas) %>% 
  slice_head(n = 3)

# Run if too few significant present 
significant_all <- prioritization[prioritization$pvalue_adjusted!=1,] %>%
  group_by(gwas) %>% 
  slice_head(n = 5)

# Create list of significant clusters
clusters <- unique(significant$annotation)

write.csv(x = as.data.frame(prioritization), file = "/home/cbmr/kzd307/gitte/hippocampus/data/Saunders2_CELLECT_adjusted")
```

